// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3668.TroBots.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;

import org.usfirst.frc3668.TroBots.RobotMap;
import org.usfirst.frc3668.TroBots.commands.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class SubChassis extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX rightDrive1 = RobotMap.subChassisrightDrive1;
    private final WPI_TalonSRX rightDrive2 = RobotMap.subChassisrightDrive2;
    private final SpeedControllerGroup rightChassisMotors = RobotMap.subChassisrightChassisMotors;
    private final WPI_TalonSRX leftDrive1 = RobotMap.subChassisleftDrive1;
    private final WPI_TalonSRX leftDrive2 = RobotMap.subChassisleftDrive2;
    private final SpeedControllerGroup leftChassisMotors = RobotMap.subChassisleftChassisMotors;
    private final DifferentialDrive differentialDrive1 = RobotMap.subChassisDifferentialDrive1;
    private final AnalogGyro gyro = RobotMap.subChassisgyro;
    private final Ultrasonic leftSonar = RobotMap.subChassisleftSonar;
    private final Ultrasonic rightSonar = RobotMap.subChassisrightSonar;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

