// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3668.TroBot.commands;

import org.usfirst.frc3668.TroBot.Robot;
import org.usfirst.frc3668.TroBot.Settings;
import org.usfirst.frc3668.TroBot.Settings.autoPosition;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutoGroupSwitch extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoGroupSwitch(autoPosition pos) {
    	double switchAngle = 0;
    	double switchDistance = 0;
    	
    	if(Robot.gameData.charAt(0) == 'L') {
    		switchAngle = Settings.autoAngleToSwitchLeft;
    		switchDistance = Settings.autoDiagToSwitchLeft;
    	}
    	if(Robot.gameData.charAt(0) == 'R') {
    		switchAngle = Settings.autoAngleToSwitchRight;
    		switchDistance = Settings.autoDiagToSwitchRight;
    	}
    	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	addSequential(new AutoDriveProfileGyro(0,Settings.autoCruiseSpeed ,Settings.autoPivotToBumper));
    	addSequential(new AutoTurnGyro(Settings.autoTurnSpeed,switchAngle));
    	addSequential(new AutoDriveProfileGyro(switchAngle ,Settings.autoCruiseSpeed ,switchDistance));
    	addSequential(new AutoTurnGyro(Settings.autoTurnSpeed,0));
    	addSequential(new AutoDriveProfileGyro(0,Settings.autoCruiseSpeed,Settings.autoPivotToBumper));
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
