package org.usfirst.frc3668.TroBot.subSystems;

import org.usfirst.frc3668.TroBot.RobotMap;
import org.usfirst.frc3668.TroBot.Settings;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.command.Subsystem;

public class SubClimb extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// private final WPI_TalonSRX climb1 = RobotMap.climb1;
	// private final WPI_TalonSRX climb2 = RobotMap.climb2;
	// private final SpeedControllerGroup climbController =
	// RobotMap.climbController;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public void climbFixedSpeed() {

		RobotMap.climb1.set(Settings.climbMotorSpeed);
		RobotMap.climb2.set(Settings.climbMotorSpeed);

	}

	public void joyClimb(Joystick joy) {
		double motorSpeed = (1 - joy.getY());
		RobotMap.climbController.set(Math.abs(joy.getY()));
	}

	public void StopClimb() {
		RobotMap.climbController.set(0);
	}

	public void initDefaultCommand() {
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop

	}

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

}
