package org.usfirst.frc3668.TroBot.subSystems;

import edu.wpi.first.wpilibj.command.Subsystem;

import org.usfirst.frc3668.TroBot.RobotMap;
import org.usfirst.frc3668.TroBot.Settings;
import org.usfirst.frc3668.TroBot.commands.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

public class SubIntake extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//    private final WPI_TalonSRX rightIntakeWheel = RobotMap.rightIntakeWheel;
//    private final WPI_TalonSRX leftIntakeWheel = RobotMap.leftIntakeWheel;
//    private final WPI_TalonSRX rightArm = RobotMap.intakeRightArm;
//    private final WPI_TalonSRX leftArm = RobotMap.intakeleftArm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public void intakeIn() {
	RobotMap.rightIntakeWheel.set(Settings.intakeRightValue);
	RobotMap.leftIntakeWheel.set(Settings.intakeLeftValue);

}

public void intakeOut() {
	RobotMap.rightIntakeWheel.set(-Settings.intakeRightValue);
	RobotMap.leftIntakeWheel.set(-Settings.intakeLeftValue);

}
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}