package org.usfirst.frc3668.TroBot.subSystems;

import edu.wpi.first.wpilibj.command.Subsystem;

import org.usfirst.frc3668.TroBot.RobotMap;
import org.usfirst.frc3668.TroBot.Settings;
import org.usfirst.frc3668.TroBot.commands.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

public class SubIntake extends Subsystem {

	public void intakeIn() {
		RobotMap.rightIntakeWheel.set(Settings.intakeRightValue);
		RobotMap.leftIntakeWheel.set(Settings.intakeLeftValue);

	}

	public void intakeOut() {
		RobotMap.rightIntakeWheel.set(-Settings.intakeRightValue);
		RobotMap.leftIntakeWheel.set(-Settings.intakeLeftValue);
	}
	
	public void stopIntake() {
		RobotMap.rightIntakeWheel.set(0);
		RobotMap.leftIntakeWheel.set(0);
	}

	@Override
	public void initDefaultCommand() {
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop
	}
}