// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3668.TroBots;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX subChassisrightDrive1;
    public static WPI_TalonSRX subChassisrightDrive2;
    public static SpeedControllerGroup subChassisrightChassisMotors;
    public static WPI_TalonSRX subChassisleftDrive1;
    public static WPI_TalonSRX subChassisleftDrive2;
    public static SpeedControllerGroup subChassisleftChassisMotors;
    public static DifferentialDrive subChassisDifferentialDrive1;
    public static AnalogGyro subChassisgyro;
    public static Ultrasonic subChassisleftSonar;
    public static Ultrasonic subChassisrightSonar;
    public static WPI_TalonSRX subIntakerightIntakeWheel;
    public static WPI_TalonSRX subIntakeleftIntakeWheel;
    public static WPI_TalonSRX subIntakerightArm;
    public static WPI_TalonSRX subIntakeleftArm;
    public static WPI_TalonSRX subLiftliftMotor;
    public static AnalogPotentiometer subLiftliftPotentiometer;
    public static WPI_TalonSRX subClimbclimb1;
    public static WPI_TalonSRX subClimbclimb2;
    public static SpeedControllerGroup subClimbclimbController;
    public static WPI_TalonSRX subTraytrayRoller;
    public static DigitalInput subTrayrightLimit;
    public static DigitalInput subTrayleftLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subChassisrightDrive1 = new WPI_TalonSRX(1);
        
        
        subChassisrightDrive2 = new WPI_TalonSRX(2);
        
        
        subChassisrightChassisMotors = new SpeedControllerGroup(subChassisrightDrive1, subChassisrightDrive2  );
        
        subChassisleftDrive1 = new WPI_TalonSRX(3);
        
        
        subChassisleftDrive2 = new WPI_TalonSRX(4);
        
        
        subChassisleftChassisMotors = new SpeedControllerGroup(subChassisleftDrive1, subChassisleftDrive2  );
        
        subChassisDifferentialDrive1 = new DifferentialDrive(subChassisleftChassisMotors, subChassisrightChassisMotors);
        subChassisDifferentialDrive1.setSafetyEnabled(true);
        subChassisDifferentialDrive1.setExpiration(0.1);
        subChassisDifferentialDrive1.setMaxOutput(1.0);

        subChassisgyro = new AnalogGyro(0);
        subChassisgyro.setSensitivity(0.007);
        subChassisleftSonar = new Ultrasonic(1, 2);
        
        subChassisrightSonar = new Ultrasonic(3, 4);
        LiveWindow.addSensor("SubChassis", "rightSonar", subChassisrightSonar);
        
        subIntakerightIntakeWheel = new WPI_TalonSRX(5);
        
        
        subIntakeleftIntakeWheel = new WPI_TalonSRX(6);
        
        
        subIntakerightArm = new WPI_TalonSRX(7);
        
        
        subIntakeleftArm = new WPI_TalonSRX(8);
        
        
        subLiftliftMotor = new WPI_TalonSRX(9);
        
        
        subLiftliftPotentiometer = new AnalogPotentiometer(2, 1.0, 0.0);
        
        subClimbclimb1 = new WPI_TalonSRX(10);
        
        
        subClimbclimb2 = new WPI_TalonSRX(11);
        
        
        subClimbclimbController = new SpeedControllerGroup(subClimbclimb1, subClimbclimb2  );
        
        subTraytrayRoller = new WPI_TalonSRX(12);
        
        
        subTrayrightLimit = new DigitalInput(6);
        
        subTrayleftLimit = new DigitalInput(5);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
